// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBOdaWAvRcSEkY1u0-NW6y6xv3zSGBP6s',
    appId: '1:153389146287:android:df65b618cd48f9e0e6745a',
    messagingSenderId: '153389146287',
    projectId: 'parking-app-cd0f0',
    databaseURL: 'https://parking-app-cd0f0-default-rtdb.firebaseio.com',
    storageBucket: 'parking-app-cd0f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyxYzuXsDgKhwSxKK6AWXYIf8V8oh_bxQ',
    appId: '1:153389146287:ios:5fecc2e6997c2828e6745a',
    messagingSenderId: '153389146287',
    projectId: 'parking-app-cd0f0',
    databaseURL: 'https://parking-app-cd0f0-default-rtdb.firebaseio.com',
    storageBucket: 'parking-app-cd0f0.appspot.com',
    androidClientId: '153389146287-879k9019e5dkpil3spp1tl5919581820.apps.googleusercontent.com',
    iosClientId: '153389146287-7ram1v9ca6aa1e8ht5r0dfkmv2em9lf0.apps.googleusercontent.com',
    iosBundleId: 'com.example.parkingAdmin',
  );
}
